# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_led_controller_0_0/design_1_led_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_led_controller_0_0 || ORIG_REF_NAME==design_1_led_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_state_machine_0_0/design_1_state_machine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_state_machine_0_0 || ORIG_REF_NAME==design_1_state_machine_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_manager_0_0/design_1_clk_manager_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_manager_0_0 || ORIG_REF_NAME==design_1_clk_manager_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_apuesta_0_0/design_1_apuesta_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_apuesta_0_0 || ORIG_REF_NAME==design_1_apuesta_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_settings_0_0/design_1_settings_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_settings_0_0 || ORIG_REF_NAME==design_1_settings_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ruleta_0_0/design_1_ruleta_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ruleta_0_0 || ORIG_REF_NAME==design_1_ruleta_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_0/design_1_debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_0 || ORIG_REF_NAME==design_1_debouncer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_1_0/design_1_debouncer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debouncer_1_0 || ORIG_REF_NAME==design_1_debouncer_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_2_0/design_1_debouncer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debouncer_2_0 || ORIG_REF_NAME==design_1_debouncer_2_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
